swagger: '2.0'
info:
  title: Product API
  description: API for managing products
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Product
    description: Endpoints for managing products
paths:
  /products:
    get:
      tags:
        - Product
      summary: Get all products
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    post:
      tags:
        - Product
      summary: Create a new product
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewProduct'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Product'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

   

      
  /products/{productId}:
    get:
      tags:
        - Product
      summary: Get a product by ID
      parameters:
        - in: path
          name: productId
          description: ID of the product to retrieve
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Product'
        404:
          description: Not Found
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
        - Product
      summary: Update an existing product
      parameters:
        - in: path
          name: productId
          description: ID of the product to update
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Product'
        404:
          description: Not Found
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

    delete:
      tags:
        - Product
      summary: Delete a product by ID
      parameters:
        - in: path
          name: productId
          description: ID of the product to delete
          required: true
          type: string
      responses:
        204:
          description: No Content
        404:
          description: Not Found
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Product:
    type: object
    properties:
      productId:
        type: string
        description: Unique identifier for the product
      productName:
        type: string
        description: Name of the product
        required: true
      productOwnerName:
        type: string
        description: Name of the product owner
        required: true
      developers:
        type: array
        items:
          type: string
        description: List of developers working on the product
        required: true
      scrumMasterName:
        type: string
        description: Name of the scrum master for the product
        required: true
      startDate:
        type: string
        format: date
        description: Date the product was started
        required: true
      methodology:
        type: string
        description: Development methodology used for the product
        required: true

  NewProduct:
    allOf:
      - $ref: '#/definitions/Product'
      - properties:
          productId:
            enum: []
            description: Excluded from the new product payload
            type: string
            readOnly: true
  
  Error:
    type: object
    properties:
      message:
        type: string
        description: Error Message
